name: Build

on:
  workflow_call:
    inputs:
      targets:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ fromJson(inputs.targets) }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Install dependencies
        run: |
          sudo apt-get update;
          sudo apt-get install -y libsasl2-dev;

      - name: Cache cargo registry + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build for ${{ matrix.target }}
        run: cargo build --features=sasl,ssl --target ${{ matrix.target }}

