name: Rust Format & Clippy

on:
  workflow_call:

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Rust (nightly)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt

      - name: Set up Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - name: Install dependencies
        run: |
          sudo apt-get update;
          sudo apt-get install -y libsasl2-dev;

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run cargo fmt --check
        run: cargo +nightly fmt --check

      - name: Run cargo clippy with features
        run: cargo +stable clippy --features=sasl,ssl -- -Dwarnings
