name: Install Cargo Make

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: "0.37.24"

jobs:
  install-cargo-make:
    runs-on: ubuntu-latest
    steps:
      - name: Download cargo-make ${{ inputs.version }}
        run: |
          curl -L -o cargo-make.zip "https://github.com/sagiegurari/cargo-make/releases/download/${{ inputs.version }}/cargo-make-v${{ inputs.version }}-x86_64-unknown-linux-gnu.zip"

      - name: Unzip and install cargo-make
        run: |
          unzip cargo-make.zip
          chmod +x cargo-make
          sudo mv cargo-make /usr/local/bin/

      - name: Check installation
        run: cargo-make --version
